frr version 8.4.1
frr defaults traditional
hostname p02
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.4/32
 ip ospf area 0.0.0.0
!
interface eth1
 ip address 10.0.0.10/30
 ip ospf area 0.0.0.0
!
interface eth2
 ip address 10.0.0.18/30
 ip ospf area 0.0.0.0
!
interface eth3
 ip address 10.0.0.14/30
 ip ospf area 0.0.0.0
!
router ospf
 ospf router-id 10.255.0.4
 router-info area 0.0.0.0
 passive-interface lo
 capability opaque
 mpls-te on
 mpls-te router-address 10.255.0.4
 segment-routing on
 segment-routing global-block 16000 19999
 segment-routing node-msd 8
 segment-routing prefix 10.255.0.4/32 index 4
!
line vty
!
