version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/build/package"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action/*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
