frr version 8.4.1
frr defaults traditional
hostname p01
service integrated-vtysh-config
!
log file /tmp/frr.log
!
interface lo
 ip address 10.255.0.2/32
 ip ospf area 0.0.0.0
!
interface eth1
 ip address 10.0.0.2/30
 ip ospf area 0.0.0.0
!
interface eth2
 ip address 10.0.0.5/30
 ip ospf area 0.0.0.0
!
interface eth3
 ip address 10.0.0.13/30
 ip ospf area 0.0.0.0
!
router ospf
 ospf router-id 10.255.0.2
 router-info area 0.0.0.0
 passive-interface lo
 capability opaque
 mpls-te on
 mpls-te router-address 10.255.0.2
 segment-routing on
 segment-routing global-block 16000 19999
 segment-routing node-msd 8
 segment-routing prefix 10.255.0.2/32 index 2
!
line vty
!
