// Copyright (c) 2022 NTT Communications Corporation
//
// This software is released under the MIT License.
// see https://github.com/nttcom/pola/blob/main/LICENSE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/pola/v1/pola.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SRPolicyType int32

const (
	SRPolicyType_SR_POLICY_TYPE_UNSPECIFIED SRPolicyType = 0
	SRPolicyType_SR_POLICY_TYPE_EXPLICIT    SRPolicyType = 1
	SRPolicyType_SR_POLICY_TYPE_DYNAMIC     SRPolicyType = 2
)

// Enum value maps for SRPolicyType.
var (
	SRPolicyType_name = map[int32]string{
		0: "SR_POLICY_TYPE_UNSPECIFIED",
		1: "SR_POLICY_TYPE_EXPLICIT",
		2: "SR_POLICY_TYPE_DYNAMIC",
	}
	SRPolicyType_value = map[string]int32{
		"SR_POLICY_TYPE_UNSPECIFIED": 0,
		"SR_POLICY_TYPE_EXPLICIT":    1,
		"SR_POLICY_TYPE_DYNAMIC":     2,
	}
)

func (x SRPolicyType) Enum() *SRPolicyType {
	p := new(SRPolicyType)
	*p = x
	return p
}

func (x SRPolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SRPolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pola_v1_pola_proto_enumTypes[0].Descriptor()
}

func (SRPolicyType) Type() protoreflect.EnumType {
	return &file_api_pola_v1_pola_proto_enumTypes[0]
}

func (x SRPolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SRPolicyType.Descriptor instead.
func (SRPolicyType) EnumDescriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{0}
}

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_DOWN        SessionState = 1
	SessionState_SESSION_STATE_UP          SessionState = 2
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_DOWN",
		2: "SESSION_STATE_UP",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_DOWN":        1,
		"SESSION_STATE_UP":          2,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pola_v1_pola_proto_enumTypes[1].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_api_pola_v1_pola_proto_enumTypes[1]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{1}
}

type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED MetricType = 0
	MetricType_METRIC_TYPE_IGP         MetricType = 1
	MetricType_METRIC_TYPE_TE          MetricType = 2
	MetricType_METRIC_TYPE_DELAY       MetricType = 3
	MetricType_METRIC_TYPE_HOPCOUNT    MetricType = 4
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_UNSPECIFIED",
		1: "METRIC_TYPE_IGP",
		2: "METRIC_TYPE_TE",
		3: "METRIC_TYPE_DELAY",
		4: "METRIC_TYPE_HOPCOUNT",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED": 0,
		"METRIC_TYPE_IGP":         1,
		"METRIC_TYPE_TE":          2,
		"METRIC_TYPE_DELAY":       3,
		"METRIC_TYPE_HOPCOUNT":    4,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pola_v1_pola_proto_enumTypes[2].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_api_pola_v1_pola_proto_enumTypes[2]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{2}
}

type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	SidStructure  string                 `protobuf:"bytes,2,opt,name=sid_structure,json=sidStructure,proto3" json:"sid_structure,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,3,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,4,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Segment) GetSidStructure() string {
	if x != nil {
		return x.SidStructure
	}
	return ""
}

func (x *Segment) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *Segment) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type Waypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Sid           string                 `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"` // optional: explicit SID override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Waypoint) Reset() {
	*x = Waypoint{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Waypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Waypoint) ProtoMessage() {}

func (x *Waypoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Waypoint.ProtoReflect.Descriptor instead.
func (*Waypoint) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{1}
}

func (x *Waypoint) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *Waypoint) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type SRPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PcepSessionAddr []byte                 `protobuf:"bytes,1,opt,name=pcep_session_addr,json=pcepSessionAddr,proto3" json:"pcep_session_addr,omitempty"`
	SrcAddr         []byte                 `protobuf:"bytes,2,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	DstAddr         []byte                 `protobuf:"bytes,3,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	SrcRouterId     string                 `protobuf:"bytes,4,opt,name=src_router_id,json=srcRouterId,proto3" json:"src_router_id,omitempty"`
	DstRouterId     string                 `protobuf:"bytes,5,opt,name=dst_router_id,json=dstRouterId,proto3" json:"dst_router_id,omitempty"`
	Color           uint32                 `protobuf:"varint,6,opt,name=color,proto3" json:"color,omitempty"`
	Preference      uint32                 `protobuf:"varint,7,opt,name=preference,proto3" json:"preference,omitempty"`
	PolicyName      string                 `protobuf:"bytes,8,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	Type            SRPolicyType           `protobuf:"varint,9,opt,name=type,proto3,enum=api.pola.v1.SRPolicyType" json:"type,omitempty"`
	SegmentList     []*Segment             `protobuf:"bytes,10,rep,name=segment_list,json=segmentList,proto3" json:"segment_list,omitempty"`
	Metric          MetricType             `protobuf:"varint,11,opt,name=metric,proto3,enum=api.pola.v1.MetricType" json:"metric,omitempty"`
	Waypoints       []*Waypoint            `protobuf:"bytes,12,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SRPolicy) Reset() {
	*x = SRPolicy{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRPolicy) ProtoMessage() {}

func (x *SRPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRPolicy.ProtoReflect.Descriptor instead.
func (*SRPolicy) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{2}
}

func (x *SRPolicy) GetPcepSessionAddr() []byte {
	if x != nil {
		return x.PcepSessionAddr
	}
	return nil
}

func (x *SRPolicy) GetSrcAddr() []byte {
	if x != nil {
		return x.SrcAddr
	}
	return nil
}

func (x *SRPolicy) GetDstAddr() []byte {
	if x != nil {
		return x.DstAddr
	}
	return nil
}

func (x *SRPolicy) GetSrcRouterId() string {
	if x != nil {
		return x.SrcRouterId
	}
	return ""
}

func (x *SRPolicy) GetDstRouterId() string {
	if x != nil {
		return x.DstRouterId
	}
	return ""
}

func (x *SRPolicy) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *SRPolicy) GetPreference() uint32 {
	if x != nil {
		return x.Preference
	}
	return 0
}

func (x *SRPolicy) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *SRPolicy) GetType() SRPolicyType {
	if x != nil {
		return x.Type
	}
	return SRPolicyType_SR_POLICY_TYPE_UNSPECIFIED
}

func (x *SRPolicy) GetSegmentList() []*Segment {
	if x != nil {
		return x.SegmentList
	}
	return nil
}

func (x *SRPolicy) GetMetric() MetricType {
	if x != nil {
		return x.Metric
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *SRPolicy) GetWaypoints() []*Waypoint {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

type CreateSRPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrPolicy      *SRPolicy              `protobuf:"bytes,1,opt,name=sr_policy,json=srPolicy,proto3" json:"sr_policy,omitempty"`
	Asn           uint32                 `protobuf:"varint,2,opt,name=asn,proto3" json:"asn,omitempty"`
	SidValidate   bool                   `protobuf:"varint,3,opt,name=sid_validate,json=sidValidate,proto3" json:"sid_validate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSRPolicyRequest) Reset() {
	*x = CreateSRPolicyRequest{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSRPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSRPolicyRequest) ProtoMessage() {}

func (x *CreateSRPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSRPolicyRequest.ProtoReflect.Descriptor instead.
func (*CreateSRPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSRPolicyRequest) GetSrPolicy() *SRPolicy {
	if x != nil {
		return x.SrPolicy
	}
	return nil
}

func (x *CreateSRPolicyRequest) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *CreateSRPolicyRequest) GetSidValidate() bool {
	if x != nil {
		return x.SidValidate
	}
	return false
}

type CreateSRPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSRPolicyResponse) Reset() {
	*x = CreateSRPolicyResponse{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSRPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSRPolicyResponse) ProtoMessage() {}

func (x *CreateSRPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSRPolicyResponse.ProtoReflect.Descriptor instead.
func (*CreateSRPolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSRPolicyResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type DeleteSRPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrPolicy      *SRPolicy              `protobuf:"bytes,1,opt,name=sr_policy,json=srPolicy,proto3" json:"sr_policy,omitempty"`
	Asn           uint32                 `protobuf:"varint,2,opt,name=asn,proto3" json:"asn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSRPolicyRequest) Reset() {
	*x = DeleteSRPolicyRequest{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSRPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSRPolicyRequest) ProtoMessage() {}

func (x *DeleteSRPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSRPolicyRequest.ProtoReflect.Descriptor instead.
func (*DeleteSRPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSRPolicyRequest) GetSrPolicy() *SRPolicy {
	if x != nil {
		return x.SrPolicy
	}
	return nil
}

func (x *DeleteSRPolicyRequest) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

type DeleteSRPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSRPolicyResponse) Reset() {
	*x = DeleteSRPolicyResponse{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSRPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSRPolicyResponse) ProtoMessage() {}

func (x *DeleteSRPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSRPolicyResponse.ProtoReflect.Descriptor instead.
func (*DeleteSRPolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSRPolicyResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          []byte                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	State         SessionState           `protobuf:"varint,2,opt,name=state,proto3,enum=api.pola.v1.SessionState" json:"state,omitempty"`
	Caps          []string               `protobuf:"bytes,3,rep,name=caps,proto3" json:"caps,omitempty"`
	IsSynced      bool                   `protobuf:"varint,4,opt,name=is_synced,json=isSynced,proto3" json:"is_synced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{7}
}

func (x *Session) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *Session) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *Session) GetCaps() []string {
	if x != nil {
		return x.Caps
	}
	return nil
}

func (x *Session) GetIsSynced() bool {
	if x != nil {
		return x.IsSynced
	}
	return false
}

type SessionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionList) Reset() {
	*x = SessionList{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionList) ProtoMessage() {}

func (x *SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionList.ProtoReflect.Descriptor instead.
func (*SessionList) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{8}
}

func (x *SessionList) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SRPolicyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrPolicies    []*SRPolicy            `protobuf:"bytes,1,rep,name=sr_policies,json=srPolicies,proto3" json:"sr_policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRPolicyList) Reset() {
	*x = SRPolicyList{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRPolicyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRPolicyList) ProtoMessage() {}

func (x *SRPolicyList) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRPolicyList.ProtoReflect.Descriptor instead.
func (*SRPolicyList) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{9}
}

func (x *SRPolicyList) GetSrPolicies() []*SRPolicy {
	if x != nil {
		return x.SrPolicies
	}
	return nil
}

type EndpointBehavior struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Behavior      uint32                 `protobuf:"varint,1,opt,name=behavior,proto3" json:"behavior,omitempty"`
	Flags         uint32                 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	Algorithm     uint32                 `protobuf:"varint,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointBehavior) Reset() {
	*x = EndpointBehavior{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointBehavior) ProtoMessage() {}

func (x *EndpointBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointBehavior.ProtoReflect.Descriptor instead.
func (*EndpointBehavior) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{10}
}

func (x *EndpointBehavior) GetBehavior() uint32 {
	if x != nil {
		return x.Behavior
	}
	return 0
}

func (x *EndpointBehavior) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *EndpointBehavior) GetAlgorithm() uint32 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

type SidStructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalBlock    uint32                 `protobuf:"varint,1,opt,name=local_block,json=localBlock,proto3" json:"local_block,omitempty"`
	LocalNode     uint32                 `protobuf:"varint,2,opt,name=local_node,json=localNode,proto3" json:"local_node,omitempty"`
	LocalFunc     uint32                 `protobuf:"varint,3,opt,name=local_func,json=localFunc,proto3" json:"local_func,omitempty"`
	LocalArg      uint32                 `protobuf:"varint,4,opt,name=local_arg,json=localArg,proto3" json:"local_arg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidStructure) Reset() {
	*x = SidStructure{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidStructure) ProtoMessage() {}

func (x *SidStructure) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidStructure.ProtoReflect.Descriptor instead.
func (*SidStructure) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{11}
}

func (x *SidStructure) GetLocalBlock() uint32 {
	if x != nil {
		return x.LocalBlock
	}
	return 0
}

func (x *SidStructure) GetLocalNode() uint32 {
	if x != nil {
		return x.LocalNode
	}
	return 0
}

func (x *SidStructure) GetLocalFunc() uint32 {
	if x != nil {
		return x.LocalFunc
	}
	return 0
}

func (x *SidStructure) GetLocalArg() uint32 {
	if x != nil {
		return x.LocalArg
	}
	return 0
}

type SID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SID) Reset() {
	*x = SID{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SID) ProtoMessage() {}

func (x *SID) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SID.ProtoReflect.Descriptor instead.
func (*SID) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{12}
}

func (x *SID) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type MultiTopoID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MultiTopoId   uint32                 `protobuf:"varint,1,opt,name=multi_topo_id,json=multiTopoId,proto3" json:"multi_topo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTopoID) Reset() {
	*x = MultiTopoID{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTopoID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTopoID) ProtoMessage() {}

func (x *MultiTopoID) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTopoID.ProtoReflect.Descriptor instead.
func (*MultiTopoID) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{13}
}

func (x *MultiTopoID) GetMultiTopoId() uint32 {
	if x != nil {
		return x.MultiTopoId
	}
	return 0
}

type LsSrv6SID struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Sids             []*SID                 `protobuf:"bytes,1,rep,name=sids,proto3" json:"sids,omitempty"`
	EndpointBehavior *EndpointBehavior      `protobuf:"bytes,2,opt,name=endpoint_behavior,json=endpointBehavior,proto3" json:"endpoint_behavior,omitempty"`
	SidStructure     *SidStructure          `protobuf:"bytes,3,opt,name=sid_structure,json=sidStructure,proto3" json:"sid_structure,omitempty"`
	MultiTopoIds     []*MultiTopoID         `protobuf:"bytes,4,rep,name=multi_topo_ids,json=multiTopoIds,proto3" json:"multi_topo_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LsSrv6SID) Reset() {
	*x = LsSrv6SID{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsSrv6SID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsSrv6SID) ProtoMessage() {}

func (x *LsSrv6SID) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsSrv6SID.ProtoReflect.Descriptor instead.
func (*LsSrv6SID) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{14}
}

func (x *LsSrv6SID) GetSids() []*SID {
	if x != nil {
		return x.Sids
	}
	return nil
}

func (x *LsSrv6SID) GetEndpointBehavior() *EndpointBehavior {
	if x != nil {
		return x.EndpointBehavior
	}
	return nil
}

func (x *LsSrv6SID) GetSidStructure() *SidStructure {
	if x != nil {
		return x.SidStructure
	}
	return nil
}

func (x *LsSrv6SID) GetMultiTopoIds() []*MultiTopoID {
	if x != nil {
		return x.MultiTopoIds
	}
	return nil
}

type LsPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	SidIndex      uint32                 `protobuf:"varint,2,opt,name=sid_index,json=sidIndex,proto3" json:"sid_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsPrefix) Reset() {
	*x = LsPrefix{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsPrefix) ProtoMessage() {}

func (x *LsPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsPrefix.ProtoReflect.Descriptor instead.
func (*LsPrefix) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{15}
}

func (x *LsPrefix) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *LsPrefix) GetSidIndex() uint32 {
	if x != nil {
		return x.SidIndex
	}
	return 0
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MetricType             `protobuf:"varint,1,opt,name=type,proto3,enum=api.pola.v1.MetricType" json:"type,omitempty"`
	Value         uint32                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{16}
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *Metric) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Srv6EndXSID struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EndpointBehavior uint32                 `protobuf:"varint,1,opt,name=endpoint_behavior,json=endpointBehavior,proto3" json:"endpoint_behavior,omitempty"`
	Sids             []*SID                 `protobuf:"bytes,2,rep,name=sids,proto3" json:"sids,omitempty"`
	SidStructure     *SidStructure          `protobuf:"bytes,3,opt,name=sid_structure,json=sidStructure,proto3" json:"sid_structure,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Srv6EndXSID) Reset() {
	*x = Srv6EndXSID{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Srv6EndXSID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Srv6EndXSID) ProtoMessage() {}

func (x *Srv6EndXSID) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Srv6EndXSID.ProtoReflect.Descriptor instead.
func (*Srv6EndXSID) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{17}
}

func (x *Srv6EndXSID) GetEndpointBehavior() uint32 {
	if x != nil {
		return x.EndpointBehavior
	}
	return 0
}

func (x *Srv6EndXSID) GetSids() []*SID {
	if x != nil {
		return x.Sids
	}
	return nil
}

func (x *Srv6EndXSID) GetSidStructure() *SidStructure {
	if x != nil {
		return x.SidStructure
	}
	return nil
}

type LsLink struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LocalRouterId  string                 `protobuf:"bytes,1,opt,name=local_router_id,json=localRouterId,proto3" json:"local_router_id,omitempty"`
	LocalAsn       uint32                 `protobuf:"varint,2,opt,name=local_asn,json=localAsn,proto3" json:"local_asn,omitempty"`
	LocalIp        string                 `protobuf:"bytes,3,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	RemoteRouterId string                 `protobuf:"bytes,4,opt,name=remote_router_id,json=remoteRouterId,proto3" json:"remote_router_id,omitempty"`
	RemoteAsn      uint32                 `protobuf:"varint,5,opt,name=remote_asn,json=remoteAsn,proto3" json:"remote_asn,omitempty"`
	RemoteIp       string                 `protobuf:"bytes,6,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	Metrics        []*Metric              `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty"`
	AdjSid         uint32                 `protobuf:"varint,8,opt,name=adj_sid,json=adjSid,proto3" json:"adj_sid,omitempty"`
	Srv6EndXSid    *Srv6EndXSID           `protobuf:"bytes,9,opt,name=srv6_end_x_sid,json=srv6EndXSid,proto3" json:"srv6_end_x_sid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LsLink) Reset() {
	*x = LsLink{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsLink) ProtoMessage() {}

func (x *LsLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsLink.ProtoReflect.Descriptor instead.
func (*LsLink) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{18}
}

func (x *LsLink) GetLocalRouterId() string {
	if x != nil {
		return x.LocalRouterId
	}
	return ""
}

func (x *LsLink) GetLocalAsn() uint32 {
	if x != nil {
		return x.LocalAsn
	}
	return 0
}

func (x *LsLink) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *LsLink) GetRemoteRouterId() string {
	if x != nil {
		return x.RemoteRouterId
	}
	return ""
}

func (x *LsLink) GetRemoteAsn() uint32 {
	if x != nil {
		return x.RemoteAsn
	}
	return 0
}

func (x *LsLink) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *LsLink) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *LsLink) GetAdjSid() uint32 {
	if x != nil {
		return x.AdjSid
	}
	return 0
}

func (x *LsLink) GetSrv6EndXSid() *Srv6EndXSID {
	if x != nil {
		return x.Srv6EndXSid
	}
	return nil
}

type LsNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	RouterId      string                 `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	IsisAreaId    string                 `protobuf:"bytes,3,opt,name=isis_area_id,json=isisAreaId,proto3" json:"isis_area_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	SrgbBegin     uint32                 `protobuf:"varint,5,opt,name=srgb_begin,json=srgbBegin,proto3" json:"srgb_begin,omitempty"`
	SrgbEnd       uint32                 `protobuf:"varint,6,opt,name=srgb_end,json=srgbEnd,proto3" json:"srgb_end,omitempty"`
	LsLinks       []*LsLink              `protobuf:"bytes,7,rep,name=ls_links,json=lsLinks,proto3" json:"ls_links,omitempty"`
	LsPrefixes    []*LsPrefix            `protobuf:"bytes,8,rep,name=ls_prefixes,json=lsPrefixes,proto3" json:"ls_prefixes,omitempty"`
	LsSrv6Sids    []*LsSrv6SID           `protobuf:"bytes,9,rep,name=ls_srv6_sids,json=lsSrv6Sids,proto3" json:"ls_srv6_sids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsNode) Reset() {
	*x = LsNode{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsNode) ProtoMessage() {}

func (x *LsNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsNode.ProtoReflect.Descriptor instead.
func (*LsNode) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{19}
}

func (x *LsNode) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *LsNode) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *LsNode) GetIsisAreaId() string {
	if x != nil {
		return x.IsisAreaId
	}
	return ""
}

func (x *LsNode) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *LsNode) GetSrgbBegin() uint32 {
	if x != nil {
		return x.SrgbBegin
	}
	return 0
}

func (x *LsNode) GetSrgbEnd() uint32 {
	if x != nil {
		return x.SrgbEnd
	}
	return 0
}

func (x *LsNode) GetLsLinks() []*LsLink {
	if x != nil {
		return x.LsLinks
	}
	return nil
}

func (x *LsNode) GetLsPrefixes() []*LsPrefix {
	if x != nil {
		return x.LsPrefixes
	}
	return nil
}

func (x *LsNode) GetLsSrv6Sids() []*LsSrv6SID {
	if x != nil {
		return x.LsSrv6Sids
	}
	return nil
}

type TED struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	LsNodes       []*LsNode              `protobuf:"bytes,2,rep,name=ls_nodes,json=lsNodes,proto3" json:"ls_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TED) Reset() {
	*x = TED{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TED) ProtoMessage() {}

func (x *TED) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TED.ProtoReflect.Descriptor instead.
func (*TED) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{20}
}

func (x *TED) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *TED) GetLsNodes() []*LsNode {
	if x != nil {
		return x.LsNodes
	}
	return nil
}

type GetSessionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionListRequest) Reset() {
	*x = GetSessionListRequest{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionListRequest) ProtoMessage() {}

func (x *GetSessionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionListRequest.ProtoReflect.Descriptor instead.
func (*GetSessionListRequest) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{21}
}

type GetSessionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionListResponse) Reset() {
	*x = GetSessionListResponse{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionListResponse) ProtoMessage() {}

func (x *GetSessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionListResponse.ProtoReflect.Descriptor instead.
func (*GetSessionListResponse) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{22}
}

func (x *GetSessionListResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSRPolicyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSRPolicyListRequest) Reset() {
	*x = GetSRPolicyListRequest{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSRPolicyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSRPolicyListRequest) ProtoMessage() {}

func (x *GetSRPolicyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSRPolicyListRequest.ProtoReflect.Descriptor instead.
func (*GetSRPolicyListRequest) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{23}
}

type GetSRPolicyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrPolicies    []*SRPolicy            `protobuf:"bytes,1,rep,name=sr_policies,json=srPolicies,proto3" json:"sr_policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSRPolicyListResponse) Reset() {
	*x = GetSRPolicyListResponse{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSRPolicyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSRPolicyListResponse) ProtoMessage() {}

func (x *GetSRPolicyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSRPolicyListResponse.ProtoReflect.Descriptor instead.
func (*GetSRPolicyListResponse) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{24}
}

func (x *GetSRPolicyListResponse) GetSrPolicies() []*SRPolicy {
	if x != nil {
		return x.SrPolicies
	}
	return nil
}

type GetTEDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTEDRequest) Reset() {
	*x = GetTEDRequest{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTEDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTEDRequest) ProtoMessage() {}

func (x *GetTEDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTEDRequest.ProtoReflect.Descriptor instead.
func (*GetTEDRequest) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{25}
}

type GetTEDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	LsNodes       []*LsNode              `protobuf:"bytes,2,rep,name=ls_nodes,json=lsNodes,proto3" json:"ls_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTEDResponse) Reset() {
	*x = GetTEDResponse{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTEDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTEDResponse) ProtoMessage() {}

func (x *GetTEDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTEDResponse.ProtoReflect.Descriptor instead.
func (*GetTEDResponse) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{26}
}

func (x *GetTEDResponse) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *GetTEDResponse) GetLsNodes() []*LsNode {
	if x != nil {
		return x.LsNodes
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          []byte                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteSessionRequest) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_api_pola_v1_pola_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pola_v1_pola_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_pola_v1_pola_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteSessionResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_api_pola_v1_pola_proto protoreflect.FileDescriptor

const file_api_pola_v1_pola_proto_rawDesc = "" +
	"\n" +
	"\x16api/pola/v1/pola.proto\x12\vapi.pola.v1\"\x80\x01\n" +
	"\aSegment\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12#\n" +
	"\rsid_structure\x18\x02 \x01(\tR\fsidStructure\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x03 \x01(\tR\tlocalAddr\x12\x1f\n" +
	"\vremote_addr\x18\x04 \x01(\tR\n" +
	"remoteAddr\"9\n" +
	"\bWaypoint\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12\x10\n" +
	"\x03sid\x18\x02 \x01(\tR\x03sid\"\xd9\x03\n" +
	"\bSRPolicy\x12*\n" +
	"\x11pcep_session_addr\x18\x01 \x01(\fR\x0fpcepSessionAddr\x12\x19\n" +
	"\bsrc_addr\x18\x02 \x01(\fR\asrcAddr\x12\x19\n" +
	"\bdst_addr\x18\x03 \x01(\fR\adstAddr\x12\"\n" +
	"\rsrc_router_id\x18\x04 \x01(\tR\vsrcRouterId\x12\"\n" +
	"\rdst_router_id\x18\x05 \x01(\tR\vdstRouterId\x12\x14\n" +
	"\x05color\x18\x06 \x01(\rR\x05color\x12\x1e\n" +
	"\n" +
	"preference\x18\a \x01(\rR\n" +
	"preference\x12\x1f\n" +
	"\vpolicy_name\x18\b \x01(\tR\n" +
	"policyName\x12-\n" +
	"\x04type\x18\t \x01(\x0e2\x19.api.pola.v1.SRPolicyTypeR\x04type\x127\n" +
	"\fsegment_list\x18\n" +
	" \x03(\v2\x14.api.pola.v1.SegmentR\vsegmentList\x12/\n" +
	"\x06metric\x18\v \x01(\x0e2\x17.api.pola.v1.MetricTypeR\x06metric\x123\n" +
	"\twaypoints\x18\f \x03(\v2\x15.api.pola.v1.WaypointR\twaypoints\"\x80\x01\n" +
	"\x15CreateSRPolicyRequest\x122\n" +
	"\tsr_policy\x18\x01 \x01(\v2\x15.api.pola.v1.SRPolicyR\bsrPolicy\x12\x10\n" +
	"\x03asn\x18\x02 \x01(\rR\x03asn\x12!\n" +
	"\fsid_validate\x18\x03 \x01(\bR\vsidValidate\"7\n" +
	"\x16CreateSRPolicyResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\"]\n" +
	"\x15DeleteSRPolicyRequest\x122\n" +
	"\tsr_policy\x18\x01 \x01(\v2\x15.api.pola.v1.SRPolicyR\bsrPolicy\x12\x10\n" +
	"\x03asn\x18\x02 \x01(\rR\x03asn\"7\n" +
	"\x16DeleteSRPolicyResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\"\x7f\n" +
	"\aSession\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\fR\x04addr\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.api.pola.v1.SessionStateR\x05state\x12\x12\n" +
	"\x04caps\x18\x03 \x03(\tR\x04caps\x12\x1b\n" +
	"\tis_synced\x18\x04 \x01(\bR\bisSynced\"?\n" +
	"\vSessionList\x120\n" +
	"\bsessions\x18\x01 \x03(\v2\x14.api.pola.v1.SessionR\bsessions\"F\n" +
	"\fSRPolicyList\x126\n" +
	"\vsr_policies\x18\x01 \x03(\v2\x15.api.pola.v1.SRPolicyR\n" +
	"srPolicies\"b\n" +
	"\x10EndpointBehavior\x12\x1a\n" +
	"\bbehavior\x18\x01 \x01(\rR\bbehavior\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\rR\talgorithm\"\x8a\x01\n" +
	"\fSidStructure\x12\x1f\n" +
	"\vlocal_block\x18\x01 \x01(\rR\n" +
	"localBlock\x12\x1d\n" +
	"\n" +
	"local_node\x18\x02 \x01(\rR\tlocalNode\x12\x1d\n" +
	"\n" +
	"local_func\x18\x03 \x01(\rR\tlocalFunc\x12\x1b\n" +
	"\tlocal_arg\x18\x04 \x01(\rR\blocalArg\"\x17\n" +
	"\x03SID\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\"1\n" +
	"\vMultiTopoID\x12\"\n" +
	"\rmulti_topo_id\x18\x01 \x01(\rR\vmultiTopoId\"\xfd\x01\n" +
	"\tLsSrv6SID\x12$\n" +
	"\x04sids\x18\x01 \x03(\v2\x10.api.pola.v1.SIDR\x04sids\x12J\n" +
	"\x11endpoint_behavior\x18\x02 \x01(\v2\x1d.api.pola.v1.EndpointBehaviorR\x10endpointBehavior\x12>\n" +
	"\rsid_structure\x18\x03 \x01(\v2\x19.api.pola.v1.SidStructureR\fsidStructure\x12>\n" +
	"\x0emulti_topo_ids\x18\x04 \x03(\v2\x18.api.pola.v1.MultiTopoIDR\fmultiTopoIds\"?\n" +
	"\bLsPrefix\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1b\n" +
	"\tsid_index\x18\x02 \x01(\rR\bsidIndex\"K\n" +
	"\x06Metric\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.api.pola.v1.MetricTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\"\xa0\x01\n" +
	"\vSrv6EndXSID\x12+\n" +
	"\x11endpoint_behavior\x18\x01 \x01(\rR\x10endpointBehavior\x12$\n" +
	"\x04sids\x18\x02 \x03(\v2\x10.api.pola.v1.SIDR\x04sids\x12>\n" +
	"\rsid_structure\x18\x03 \x01(\v2\x19.api.pola.v1.SidStructureR\fsidStructure\"\xd5\x02\n" +
	"\x06LsLink\x12&\n" +
	"\x0flocal_router_id\x18\x01 \x01(\tR\rlocalRouterId\x12\x1b\n" +
	"\tlocal_asn\x18\x02 \x01(\rR\blocalAsn\x12\x19\n" +
	"\blocal_ip\x18\x03 \x01(\tR\alocalIp\x12(\n" +
	"\x10remote_router_id\x18\x04 \x01(\tR\x0eremoteRouterId\x12\x1d\n" +
	"\n" +
	"remote_asn\x18\x05 \x01(\rR\tremoteAsn\x12\x1b\n" +
	"\tremote_ip\x18\x06 \x01(\tR\bremoteIp\x12-\n" +
	"\ametrics\x18\a \x03(\v2\x13.api.pola.v1.MetricR\ametrics\x12\x17\n" +
	"\aadj_sid\x18\b \x01(\rR\x06adjSid\x12=\n" +
	"\x0esrv6_end_x_sid\x18\t \x01(\v2\x18.api.pola.v1.Srv6EndXSIDR\vsrv6EndXSid\"\xd1\x02\n" +
	"\x06LsNode\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x1b\n" +
	"\trouter_id\x18\x02 \x01(\tR\brouterId\x12 \n" +
	"\fisis_area_id\x18\x03 \x01(\tR\n" +
	"isisAreaId\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"srgb_begin\x18\x05 \x01(\rR\tsrgbBegin\x12\x19\n" +
	"\bsrgb_end\x18\x06 \x01(\rR\asrgbEnd\x12.\n" +
	"\bls_links\x18\a \x03(\v2\x13.api.pola.v1.LsLinkR\alsLinks\x126\n" +
	"\vls_prefixes\x18\b \x03(\v2\x15.api.pola.v1.LsPrefixR\n" +
	"lsPrefixes\x128\n" +
	"\fls_srv6_sids\x18\t \x03(\v2\x16.api.pola.v1.LsSrv6SIDR\n" +
	"lsSrv6Sids\"M\n" +
	"\x03TED\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12.\n" +
	"\bls_nodes\x18\x02 \x03(\v2\x13.api.pola.v1.LsNodeR\alsNodes\"\x17\n" +
	"\x15GetSessionListRequest\"J\n" +
	"\x16GetSessionListResponse\x120\n" +
	"\bsessions\x18\x01 \x03(\v2\x14.api.pola.v1.SessionR\bsessions\"\x18\n" +
	"\x16GetSRPolicyListRequest\"Q\n" +
	"\x17GetSRPolicyListResponse\x126\n" +
	"\vsr_policies\x18\x01 \x03(\v2\x15.api.pola.v1.SRPolicyR\n" +
	"srPolicies\"\x0f\n" +
	"\rGetTEDRequest\"X\n" +
	"\x0eGetTEDResponse\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12.\n" +
	"\bls_nodes\x18\x02 \x03(\v2\x13.api.pola.v1.LsNodeR\alsNodes\"*\n" +
	"\x14DeleteSessionRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\fR\x04addr\"6\n" +
	"\x15DeleteSessionResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess*g\n" +
	"\fSRPolicyType\x12\x1e\n" +
	"\x1aSR_POLICY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SR_POLICY_TYPE_EXPLICIT\x10\x01\x12\x1a\n" +
	"\x16SR_POLICY_TYPE_DYNAMIC\x10\x02*[\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SESSION_STATE_DOWN\x10\x01\x12\x14\n" +
	"\x10SESSION_STATE_UP\x10\x02*\x83\x01\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fMETRIC_TYPE_IGP\x10\x01\x12\x12\n" +
	"\x0eMETRIC_TYPE_TE\x10\x02\x12\x15\n" +
	"\x11METRIC_TYPE_DELAY\x10\x03\x12\x18\n" +
	"\x14METRIC_TYPE_HOPCOUNT\x10\x042\x96\x04\n" +
	"\n" +
	"PCEService\x12Y\n" +
	"\x0eCreateSRPolicy\x12\".api.pola.v1.CreateSRPolicyRequest\x1a#.api.pola.v1.CreateSRPolicyResponse\x12Y\n" +
	"\x0eDeleteSRPolicy\x12\".api.pola.v1.DeleteSRPolicyRequest\x1a#.api.pola.v1.DeleteSRPolicyResponse\x12Y\n" +
	"\x0eGetSessionList\x12\".api.pola.v1.GetSessionListRequest\x1a#.api.pola.v1.GetSessionListResponse\x12\\\n" +
	"\x0fGetSRPolicyList\x12#.api.pola.v1.GetSRPolicyListRequest\x1a$.api.pola.v1.GetSRPolicyListResponse\x12A\n" +
	"\x06GetTED\x12\x1a.api.pola.v1.GetTEDRequest\x1a\x1b.api.pola.v1.GetTEDResponse\x12V\n" +
	"\rDeleteSession\x12!.api.pola.v1.DeleteSessionRequest\x1a\".api.pola.v1.DeleteSessionResponseB$Z\"github.com/nttcom/pola/api/pola/v1b\x06proto3"

var (
	file_api_pola_v1_pola_proto_rawDescOnce sync.Once
	file_api_pola_v1_pola_proto_rawDescData []byte
)

func file_api_pola_v1_pola_proto_rawDescGZIP() []byte {
	file_api_pola_v1_pola_proto_rawDescOnce.Do(func() {
		file_api_pola_v1_pola_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pola_v1_pola_proto_rawDesc), len(file_api_pola_v1_pola_proto_rawDesc)))
	})
	return file_api_pola_v1_pola_proto_rawDescData
}

var file_api_pola_v1_pola_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_pola_v1_pola_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_pola_v1_pola_proto_goTypes = []any{
	(SRPolicyType)(0),               // 0: api.pola.v1.SRPolicyType
	(SessionState)(0),               // 1: api.pola.v1.SessionState
	(MetricType)(0),                 // 2: api.pola.v1.MetricType
	(*Segment)(nil),                 // 3: api.pola.v1.Segment
	(*Waypoint)(nil),                // 4: api.pola.v1.Waypoint
	(*SRPolicy)(nil),                // 5: api.pola.v1.SRPolicy
	(*CreateSRPolicyRequest)(nil),   // 6: api.pola.v1.CreateSRPolicyRequest
	(*CreateSRPolicyResponse)(nil),  // 7: api.pola.v1.CreateSRPolicyResponse
	(*DeleteSRPolicyRequest)(nil),   // 8: api.pola.v1.DeleteSRPolicyRequest
	(*DeleteSRPolicyResponse)(nil),  // 9: api.pola.v1.DeleteSRPolicyResponse
	(*Session)(nil),                 // 10: api.pola.v1.Session
	(*SessionList)(nil),             // 11: api.pola.v1.SessionList
	(*SRPolicyList)(nil),            // 12: api.pola.v1.SRPolicyList
	(*EndpointBehavior)(nil),        // 13: api.pola.v1.EndpointBehavior
	(*SidStructure)(nil),            // 14: api.pola.v1.SidStructure
	(*SID)(nil),                     // 15: api.pola.v1.SID
	(*MultiTopoID)(nil),             // 16: api.pola.v1.MultiTopoID
	(*LsSrv6SID)(nil),               // 17: api.pola.v1.LsSrv6SID
	(*LsPrefix)(nil),                // 18: api.pola.v1.LsPrefix
	(*Metric)(nil),                  // 19: api.pola.v1.Metric
	(*Srv6EndXSID)(nil),             // 20: api.pola.v1.Srv6EndXSID
	(*LsLink)(nil),                  // 21: api.pola.v1.LsLink
	(*LsNode)(nil),                  // 22: api.pola.v1.LsNode
	(*TED)(nil),                     // 23: api.pola.v1.TED
	(*GetSessionListRequest)(nil),   // 24: api.pola.v1.GetSessionListRequest
	(*GetSessionListResponse)(nil),  // 25: api.pola.v1.GetSessionListResponse
	(*GetSRPolicyListRequest)(nil),  // 26: api.pola.v1.GetSRPolicyListRequest
	(*GetSRPolicyListResponse)(nil), // 27: api.pola.v1.GetSRPolicyListResponse
	(*GetTEDRequest)(nil),           // 28: api.pola.v1.GetTEDRequest
	(*GetTEDResponse)(nil),          // 29: api.pola.v1.GetTEDResponse
	(*DeleteSessionRequest)(nil),    // 30: api.pola.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),   // 31: api.pola.v1.DeleteSessionResponse
}
var file_api_pola_v1_pola_proto_depIdxs = []int32{
	0,  // 0: api.pola.v1.SRPolicy.type:type_name -> api.pola.v1.SRPolicyType
	3,  // 1: api.pola.v1.SRPolicy.segment_list:type_name -> api.pola.v1.Segment
	2,  // 2: api.pola.v1.SRPolicy.metric:type_name -> api.pola.v1.MetricType
	4,  // 3: api.pola.v1.SRPolicy.waypoints:type_name -> api.pola.v1.Waypoint
	5,  // 4: api.pola.v1.CreateSRPolicyRequest.sr_policy:type_name -> api.pola.v1.SRPolicy
	5,  // 5: api.pola.v1.DeleteSRPolicyRequest.sr_policy:type_name -> api.pola.v1.SRPolicy
	1,  // 6: api.pola.v1.Session.state:type_name -> api.pola.v1.SessionState
	10, // 7: api.pola.v1.SessionList.sessions:type_name -> api.pola.v1.Session
	5,  // 8: api.pola.v1.SRPolicyList.sr_policies:type_name -> api.pola.v1.SRPolicy
	15, // 9: api.pola.v1.LsSrv6SID.sids:type_name -> api.pola.v1.SID
	13, // 10: api.pola.v1.LsSrv6SID.endpoint_behavior:type_name -> api.pola.v1.EndpointBehavior
	14, // 11: api.pola.v1.LsSrv6SID.sid_structure:type_name -> api.pola.v1.SidStructure
	16, // 12: api.pola.v1.LsSrv6SID.multi_topo_ids:type_name -> api.pola.v1.MultiTopoID
	2,  // 13: api.pola.v1.Metric.type:type_name -> api.pola.v1.MetricType
	15, // 14: api.pola.v1.Srv6EndXSID.sids:type_name -> api.pola.v1.SID
	14, // 15: api.pola.v1.Srv6EndXSID.sid_structure:type_name -> api.pola.v1.SidStructure
	19, // 16: api.pola.v1.LsLink.metrics:type_name -> api.pola.v1.Metric
	20, // 17: api.pola.v1.LsLink.srv6_end_x_sid:type_name -> api.pola.v1.Srv6EndXSID
	21, // 18: api.pola.v1.LsNode.ls_links:type_name -> api.pola.v1.LsLink
	18, // 19: api.pola.v1.LsNode.ls_prefixes:type_name -> api.pola.v1.LsPrefix
	17, // 20: api.pola.v1.LsNode.ls_srv6_sids:type_name -> api.pola.v1.LsSrv6SID
	22, // 21: api.pola.v1.TED.ls_nodes:type_name -> api.pola.v1.LsNode
	10, // 22: api.pola.v1.GetSessionListResponse.sessions:type_name -> api.pola.v1.Session
	5,  // 23: api.pola.v1.GetSRPolicyListResponse.sr_policies:type_name -> api.pola.v1.SRPolicy
	22, // 24: api.pola.v1.GetTEDResponse.ls_nodes:type_name -> api.pola.v1.LsNode
	6,  // 25: api.pola.v1.PCEService.CreateSRPolicy:input_type -> api.pola.v1.CreateSRPolicyRequest
	8,  // 26: api.pola.v1.PCEService.DeleteSRPolicy:input_type -> api.pola.v1.DeleteSRPolicyRequest
	24, // 27: api.pola.v1.PCEService.GetSessionList:input_type -> api.pola.v1.GetSessionListRequest
	26, // 28: api.pola.v1.PCEService.GetSRPolicyList:input_type -> api.pola.v1.GetSRPolicyListRequest
	28, // 29: api.pola.v1.PCEService.GetTED:input_type -> api.pola.v1.GetTEDRequest
	30, // 30: api.pola.v1.PCEService.DeleteSession:input_type -> api.pola.v1.DeleteSessionRequest
	7,  // 31: api.pola.v1.PCEService.CreateSRPolicy:output_type -> api.pola.v1.CreateSRPolicyResponse
	9,  // 32: api.pola.v1.PCEService.DeleteSRPolicy:output_type -> api.pola.v1.DeleteSRPolicyResponse
	25, // 33: api.pola.v1.PCEService.GetSessionList:output_type -> api.pola.v1.GetSessionListResponse
	27, // 34: api.pola.v1.PCEService.GetSRPolicyList:output_type -> api.pola.v1.GetSRPolicyListResponse
	29, // 35: api.pola.v1.PCEService.GetTED:output_type -> api.pola.v1.GetTEDResponse
	31, // 36: api.pola.v1.PCEService.DeleteSession:output_type -> api.pola.v1.DeleteSessionResponse
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_pola_v1_pola_proto_init() }
func file_api_pola_v1_pola_proto_init() {
	if File_api_pola_v1_pola_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pola_v1_pola_proto_rawDesc), len(file_api_pola_v1_pola_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pola_v1_pola_proto_goTypes,
		DependencyIndexes: file_api_pola_v1_pola_proto_depIdxs,
		EnumInfos:         file_api_pola_v1_pola_proto_enumTypes,
		MessageInfos:      file_api_pola_v1_pola_proto_msgTypes,
	}.Build()
	File_api_pola_v1_pola_proto = out.File
	file_api_pola_v1_pola_proto_goTypes = nil
	file_api_pola_v1_pola_proto_depIdxs = nil
}
