// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PCEServiceClient is the client API for PCEService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PCEServiceClient interface {
	CreateSRPolicy(ctx context.Context, in *CreateSRPolicyRequest, opts ...grpc.CallOption) (*CreateSRPolicyResponse, error)
	DeleteSRPolicy(ctx context.Context, in *DeleteSRPolicyRequest, opts ...grpc.CallOption) (*DeleteSRPolicyResponse, error)
	GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*GetSessionListResponse, error)
	GetSRPolicyList(ctx context.Context, in *GetSRPolicyListRequest, opts ...grpc.CallOption) (*GetSRPolicyListResponse, error)
	GetTED(ctx context.Context, in *GetTEDRequest, opts ...grpc.CallOption) (*GetTEDResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
}

type pCEServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPCEServiceClient(cc grpc.ClientConnInterface) PCEServiceClient {
	return &pCEServiceClient{cc}
}

func (c *pCEServiceClient) CreateSRPolicy(ctx context.Context, in *CreateSRPolicyRequest, opts ...grpc.CallOption) (*CreateSRPolicyResponse, error) {
	out := new(CreateSRPolicyResponse)
	err := c.cc.Invoke(ctx, "/api.pola.v1.PCEService/CreateSRPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) DeleteSRPolicy(ctx context.Context, in *DeleteSRPolicyRequest, opts ...grpc.CallOption) (*DeleteSRPolicyResponse, error) {
	out := new(DeleteSRPolicyResponse)
	err := c.cc.Invoke(ctx, "/api.pola.v1.PCEService/DeleteSRPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*GetSessionListResponse, error) {
	out := new(GetSessionListResponse)
	err := c.cc.Invoke(ctx, "/api.pola.v1.PCEService/GetSessionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetSRPolicyList(ctx context.Context, in *GetSRPolicyListRequest, opts ...grpc.CallOption) (*GetSRPolicyListResponse, error) {
	out := new(GetSRPolicyListResponse)
	err := c.cc.Invoke(ctx, "/api.pola.v1.PCEService/GetSRPolicyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetTED(ctx context.Context, in *GetTEDRequest, opts ...grpc.CallOption) (*GetTEDResponse, error) {
	out := new(GetTEDResponse)
	err := c.cc.Invoke(ctx, "/api.pola.v1.PCEService/GetTED", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, "/api.pola.v1.PCEService/DeleteSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PCEServiceServer is the server API for PCEService service.
// All implementations must embed UnimplementedPCEServiceServer
// for forward compatibility
type PCEServiceServer interface {
	CreateSRPolicy(context.Context, *CreateSRPolicyRequest) (*CreateSRPolicyResponse, error)
	DeleteSRPolicy(context.Context, *DeleteSRPolicyRequest) (*DeleteSRPolicyResponse, error)
	GetSessionList(context.Context, *GetSessionListRequest) (*GetSessionListResponse, error)
	GetSRPolicyList(context.Context, *GetSRPolicyListRequest) (*GetSRPolicyListResponse, error)
	GetTED(context.Context, *GetTEDRequest) (*GetTEDResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	mustEmbedUnimplementedPCEServiceServer()
}

// UnimplementedPCEServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPCEServiceServer struct {
}

func (UnimplementedPCEServiceServer) CreateSRPolicy(context.Context, *CreateSRPolicyRequest) (*CreateSRPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSRPolicy not implemented")
}
func (UnimplementedPCEServiceServer) DeleteSRPolicy(context.Context, *DeleteSRPolicyRequest) (*DeleteSRPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSRPolicy not implemented")
}
func (UnimplementedPCEServiceServer) GetSessionList(context.Context, *GetSessionListRequest) (*GetSessionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionList not implemented")
}
func (UnimplementedPCEServiceServer) GetSRPolicyList(context.Context, *GetSRPolicyListRequest) (*GetSRPolicyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSRPolicyList not implemented")
}
func (UnimplementedPCEServiceServer) GetTED(context.Context, *GetTEDRequest) (*GetTEDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTED not implemented")
}
func (UnimplementedPCEServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedPCEServiceServer) mustEmbedUnimplementedPCEServiceServer() {}

// UnsafePCEServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PCEServiceServer will
// result in compilation errors.
type UnsafePCEServiceServer interface {
	mustEmbedUnimplementedPCEServiceServer()
}

func RegisterPCEServiceServer(s grpc.ServiceRegistrar, srv PCEServiceServer) {
	s.RegisterService(&PCEService_ServiceDesc, srv)
}

func _PCEService_CreateSRPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSRPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).CreateSRPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pola.v1.PCEService/CreateSRPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).CreateSRPolicy(ctx, req.(*CreateSRPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_DeleteSRPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSRPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).DeleteSRPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pola.v1.PCEService/DeleteSRPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).DeleteSRPolicy(ctx, req.(*DeleteSRPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetSessionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetSessionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pola.v1.PCEService/GetSessionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetSessionList(ctx, req.(*GetSessionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetSRPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSRPolicyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetSRPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pola.v1.PCEService/GetSRPolicyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetSRPolicyList(ctx, req.(*GetSRPolicyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetTED_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTEDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetTED(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pola.v1.PCEService/GetTED",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetTED(ctx, req.(*GetTEDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pola.v1.PCEService/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PCEService_ServiceDesc is the grpc.ServiceDesc for PCEService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PCEService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.pola.v1.PCEService",
	HandlerType: (*PCEServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSRPolicy",
			Handler:    _PCEService_CreateSRPolicy_Handler,
		},
		{
			MethodName: "DeleteSRPolicy",
			Handler:    _PCEService_DeleteSRPolicy_Handler,
		},
		{
			MethodName: "GetSessionList",
			Handler:    _PCEService_GetSessionList_Handler,
		},
		{
			MethodName: "GetSRPolicyList",
			Handler:    _PCEService_GetSRPolicyList_Handler,
		},
		{
			MethodName: "GetTED",
			Handler:    _PCEService_GetTED_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _PCEService_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pola.proto",
}
