frr version 8.4.1
frr defaults traditional
hostname pe02
service integrated-vtysh-config
!
log file /var/log/frr/frr.log
!
vrf cust-a
 exit-vrf
!
interface lo
 ip address 10.255.0.3/32
 ip ospf area 0.0.0.0
!
interface eth1
 ip address 10.0.0.6/30
 ip ospf area 0.0.0.0
!
interface eth2
 ip address 10.0.0.17/30
 ip ospf area 0.0.0.0
!
interface eth3 vrf cust-a
 ip address 192.168.1.1/24
!
interface eth4
 ip address 10.0.255.2/24
!
router ospf
 ospf router-id 10.255.0.3
 router-info area 0.0.0.0
 passive-interface lo
 capability opaque
 mpls-te on
 mpls-te router-address 10.255.0.3
 segment-routing on
 segment-routing global-block 16000 19999
 segment-routing node-msd 8
 segment-routing prefix 10.255.0.3/32 index 3
!
router bgp 65000
 neighbor 10.255.0.1 remote-as 65000
 neighbor 10.255.0.1 update-source 10.255.0.3
 address-family ipv4 vpn
  neighbor 10.255.0.1 activate
 exit-address-family
!
router bgp 65000 vrf cust-a
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65000:10
  rt vpn both 65000:10
  export vpn
  import vpn
 exit-address-family
!
segment-routing
 traffic-eng
  pcep
   pce POLA
    address ip 10.0.255.254
    source-address ip 10.0.255.2
    pce-initiated
   exit
   pcc
    peer POLA
   exit
  exit
 exit
!
line vty
!
