// Copyright (c) 2022 NTT Communications Corporation
//
// This software is released under the MIT License.
// see https://github.com/nttcom/pola/blob/main/LICENSE

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: pola.proto

package grpc

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PceServiceClient is the client API for PceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PceServiceClient interface {
	CreateSrPolicy(ctx context.Context, in *CreateSrPolicyInput, opts ...grpc.CallOption) (*SrPolicyStatus, error)
	CreateSrPolicyWithoutLinkState(ctx context.Context, in *CreateSrPolicyInput, opts ...grpc.CallOption) (*SrPolicyStatus, error)
	GetPeerAddrList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PeerAddrList, error)
	GetSrPolicyList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SrPolicyList, error)
	GetTed(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Ted, error)
}

type pceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPceServiceClient(cc grpc.ClientConnInterface) PceServiceClient {
	return &pceServiceClient{cc}
}

func (c *pceServiceClient) CreateSrPolicy(ctx context.Context, in *CreateSrPolicyInput, opts ...grpc.CallOption) (*SrPolicyStatus, error) {
	out := new(SrPolicyStatus)
	err := c.cc.Invoke(ctx, "/pb.PceService/CreateSrPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pceServiceClient) CreateSrPolicyWithoutLinkState(ctx context.Context, in *CreateSrPolicyInput, opts ...grpc.CallOption) (*SrPolicyStatus, error) {
	out := new(SrPolicyStatus)
	err := c.cc.Invoke(ctx, "/pb.PceService/CreateSrPolicyWithoutLinkState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pceServiceClient) GetPeerAddrList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PeerAddrList, error) {
	out := new(PeerAddrList)
	err := c.cc.Invoke(ctx, "/pb.PceService/GetPeerAddrList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pceServiceClient) GetSrPolicyList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SrPolicyList, error) {
	out := new(SrPolicyList)
	err := c.cc.Invoke(ctx, "/pb.PceService/GetSrPolicyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pceServiceClient) GetTed(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Ted, error) {
	out := new(Ted)
	err := c.cc.Invoke(ctx, "/pb.PceService/GetTed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PceServiceServer is the server API for PceService service.
// All implementations must embed UnimplementedPceServiceServer
// for forward compatibility
type PceServiceServer interface {
	CreateSrPolicy(context.Context, *CreateSrPolicyInput) (*SrPolicyStatus, error)
	CreateSrPolicyWithoutLinkState(context.Context, *CreateSrPolicyInput) (*SrPolicyStatus, error)
	GetPeerAddrList(context.Context, *empty.Empty) (*PeerAddrList, error)
	GetSrPolicyList(context.Context, *empty.Empty) (*SrPolicyList, error)
	GetTed(context.Context, *empty.Empty) (*Ted, error)
	mustEmbedUnimplementedPceServiceServer()
}

// UnimplementedPceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPceServiceServer struct {
}

func (UnimplementedPceServiceServer) CreateSrPolicy(context.Context, *CreateSrPolicyInput) (*SrPolicyStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSrPolicy not implemented")
}
func (UnimplementedPceServiceServer) CreateSrPolicyWithoutLinkState(context.Context, *CreateSrPolicyInput) (*SrPolicyStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSrPolicyWithoutLinkState not implemented")
}
func (UnimplementedPceServiceServer) GetPeerAddrList(context.Context, *empty.Empty) (*PeerAddrList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeerAddrList not implemented")
}
func (UnimplementedPceServiceServer) GetSrPolicyList(context.Context, *empty.Empty) (*SrPolicyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSrPolicyList not implemented")
}
func (UnimplementedPceServiceServer) GetTed(context.Context, *empty.Empty) (*Ted, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTed not implemented")
}
func (UnimplementedPceServiceServer) mustEmbedUnimplementedPceServiceServer() {}

// UnsafePceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PceServiceServer will
// result in compilation errors.
type UnsafePceServiceServer interface {
	mustEmbedUnimplementedPceServiceServer()
}

func RegisterPceServiceServer(s grpc.ServiceRegistrar, srv PceServiceServer) {
	s.RegisterService(&PceService_ServiceDesc, srv)
}

func _PceService_CreateSrPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSrPolicyInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PceServiceServer).CreateSrPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PceService/CreateSrPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PceServiceServer).CreateSrPolicy(ctx, req.(*CreateSrPolicyInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PceService_CreateSrPolicyWithoutLinkState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSrPolicyInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PceServiceServer).CreateSrPolicyWithoutLinkState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PceService/CreateSrPolicyWithoutLinkState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PceServiceServer).CreateSrPolicyWithoutLinkState(ctx, req.(*CreateSrPolicyInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PceService_GetPeerAddrList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PceServiceServer).GetPeerAddrList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PceService/GetPeerAddrList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PceServiceServer).GetPeerAddrList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PceService_GetSrPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PceServiceServer).GetSrPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PceService/GetSrPolicyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PceServiceServer).GetSrPolicyList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PceService_GetTed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PceServiceServer).GetTed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PceService/GetTed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PceServiceServer).GetTed(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PceService_ServiceDesc is the grpc.ServiceDesc for PceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PceService",
	HandlerType: (*PceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSrPolicy",
			Handler:    _PceService_CreateSrPolicy_Handler,
		},
		{
			MethodName: "CreateSrPolicyWithoutLinkState",
			Handler:    _PceService_CreateSrPolicyWithoutLinkState_Handler,
		},
		{
			MethodName: "GetPeerAddrList",
			Handler:    _PceService_GetPeerAddrList_Handler,
		},
		{
			MethodName: "GetSrPolicyList",
			Handler:    _PceService_GetSrPolicyList_Handler,
		},
		{
			MethodName: "GetTed",
			Handler:    _PceService_GetTed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pola.proto",
}
