// Copyright (c) 2022 NTT Communications Corporation
//
// This software is released under the MIT License.
// see https://github.com/nttcom/pola/blob/main/LICENSE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: pola.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Label struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid    uint32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	LoAddr []byte `protobuf:"bytes,2,opt,name=loAddr,proto3" json:"loAddr,omitempty"`
}

func (x *Label) Reset() {
	*x = Label{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pola_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_pola_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_pola_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *Label) GetLoAddr() []byte {
	if x != nil {
		return x.LoAddr
	}
	return nil
}

type LspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PcepSessionAddr []byte   `protobuf:"bytes,1,opt,name=pcepSessionAddr,proto3" json:"pcepSessionAddr,omitempty"`
	SrcAddr         []byte   `protobuf:"bytes,2,opt,name=srcAddr,proto3" json:"srcAddr,omitempty"`
	DstAddr         []byte   `protobuf:"bytes,3,opt,name=dstAddr,proto3" json:"dstAddr,omitempty"`
	Labels          []*Label `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Color           uint32   `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	PolicyName      string   `protobuf:"bytes,6,opt,name=policyName,proto3" json:"policyName,omitempty"`
}

func (x *LspData) Reset() {
	*x = LspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pola_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LspData) ProtoMessage() {}

func (x *LspData) ProtoReflect() protoreflect.Message {
	mi := &file_pola_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LspData.ProtoReflect.Descriptor instead.
func (*LspData) Descriptor() ([]byte, []int) {
	return file_pola_proto_rawDescGZIP(), []int{1}
}

func (x *LspData) GetPcepSessionAddr() []byte {
	if x != nil {
		return x.PcepSessionAddr
	}
	return nil
}

func (x *LspData) GetSrcAddr() []byte {
	if x != nil {
		return x.SrcAddr
	}
	return nil
}

func (x *LspData) GetDstAddr() []byte {
	if x != nil {
		return x.DstAddr
	}
	return nil
}

func (x *LspData) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LspData) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *LspData) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

type LspStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
}

func (x *LspStatus) Reset() {
	*x = LspStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pola_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LspStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LspStatus) ProtoMessage() {}

func (x *LspStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pola_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LspStatus.ProtoReflect.Descriptor instead.
func (*LspStatus) Descriptor() ([]byte, []int) {
	return file_pola_proto_rawDescGZIP(), []int{2}
}

func (x *LspStatus) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_pola_proto protoreflect.FileDescriptor

var file_pola_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6f, 0x6c, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x31, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x6f, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6c, 0x6f, 0x41,
	0x64, 0x64, 0x72, 0x22, 0xc0, 0x01, 0x0a, 0x07, 0x4c, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x28, 0x0a, 0x0f, 0x70, 0x63, 0x65, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x64,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x70, 0x63, 0x65, 0x70, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x72, 0x63,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x72, 0x63, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x64, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x21, 0x0a,
	0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x09, 0x4c, 0x73, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x32, 0x37, 0x0a, 0x0a, 0x50, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x29, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x73, 0x70, 0x12, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x73, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x74, 0x74, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x6f, 0x6c, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pola_proto_rawDescOnce sync.Once
	file_pola_proto_rawDescData = file_pola_proto_rawDesc
)

func file_pola_proto_rawDescGZIP() []byte {
	file_pola_proto_rawDescOnce.Do(func() {
		file_pola_proto_rawDescData = protoimpl.X.CompressGZIP(file_pola_proto_rawDescData)
	})
	return file_pola_proto_rawDescData
}

var file_pola_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pola_proto_goTypes = []interface{}{
	(*Label)(nil),     // 0: pb.Label
	(*LspData)(nil),   // 1: pb.LspData
	(*LspStatus)(nil), // 2: pb.LspStatus
}
var file_pola_proto_depIdxs = []int32{
	0, // 0: pb.LspData.labels:type_name -> pb.Label
	1, // 1: pb.PceService.CreateLsp:input_type -> pb.LspData
	2, // 2: pb.PceService.CreateLsp:output_type -> pb.LspStatus
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pola_proto_init() }
func file_pola_proto_init() {
	if File_pola_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pola_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Label); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pola_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pola_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LspStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pola_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pola_proto_goTypes,
		DependencyIndexes: file_pola_proto_depIdxs,
		MessageInfos:      file_pola_proto_msgTypes,
	}.Build()
	File_pola_proto = out.File
	file_pola_proto_rawDesc = nil
	file_pola_proto_goTypes = nil
	file_pola_proto_depIdxs = nil
}
