// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PCEServiceClient is the client API for PCEService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PCEServiceClient interface {
	CreateSRPolicy(ctx context.Context, in *CreateSRPolicyInput, opts ...grpc.CallOption) (*RequestStatus, error)
	CreateSRPolicyWithoutLinkState(ctx context.Context, in *CreateSRPolicyInput, opts ...grpc.CallOption) (*RequestStatus, error)
	DeleteSRPolicy(ctx context.Context, in *DeleteSRPolicyInput, opts ...grpc.CallOption) (*RequestStatus, error)
	DeleteSRPolicyWithoutLinkState(ctx context.Context, in *DeleteSRPolicyInput, opts ...grpc.CallOption) (*RequestStatus, error)
	GetSessionList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SessionList, error)
	GetSRPolicyList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SRPolicyList, error)
	GetTED(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TED, error)
	DeleteSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*RequestStatus, error)
}

type pCEServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPCEServiceClient(cc grpc.ClientConnInterface) PCEServiceClient {
	return &pCEServiceClient{cc}
}

func (c *pCEServiceClient) CreateSRPolicy(ctx context.Context, in *CreateSRPolicyInput, opts ...grpc.CallOption) (*RequestStatus, error) {
	out := new(RequestStatus)
	err := c.cc.Invoke(ctx, "/pb.PCEService/CreateSRPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) CreateSRPolicyWithoutLinkState(ctx context.Context, in *CreateSRPolicyInput, opts ...grpc.CallOption) (*RequestStatus, error) {
	out := new(RequestStatus)
	err := c.cc.Invoke(ctx, "/pb.PCEService/CreateSRPolicyWithoutLinkState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) DeleteSRPolicy(ctx context.Context, in *DeleteSRPolicyInput, opts ...grpc.CallOption) (*RequestStatus, error) {
	out := new(RequestStatus)
	err := c.cc.Invoke(ctx, "/pb.PCEService/DeleteSRPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) DeleteSRPolicyWithoutLinkState(ctx context.Context, in *DeleteSRPolicyInput, opts ...grpc.CallOption) (*RequestStatus, error) {
	out := new(RequestStatus)
	err := c.cc.Invoke(ctx, "/pb.PCEService/DeleteSRPolicyWithoutLinkState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetSessionList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SessionList, error) {
	out := new(SessionList)
	err := c.cc.Invoke(ctx, "/pb.PCEService/GetSessionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetSRPolicyList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SRPolicyList, error) {
	out := new(SRPolicyList)
	err := c.cc.Invoke(ctx, "/pb.PCEService/GetSRPolicyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetTED(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TED, error) {
	out := new(TED)
	err := c.cc.Invoke(ctx, "/pb.PCEService/GetTED", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) DeleteSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*RequestStatus, error) {
	out := new(RequestStatus)
	err := c.cc.Invoke(ctx, "/pb.PCEService/DeleteSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PCEServiceServer is the server API for PCEService service.
// All implementations must embed UnimplementedPCEServiceServer
// for forward compatibility
type PCEServiceServer interface {
	CreateSRPolicy(context.Context, *CreateSRPolicyInput) (*RequestStatus, error)
	CreateSRPolicyWithoutLinkState(context.Context, *CreateSRPolicyInput) (*RequestStatus, error)
	DeleteSRPolicy(context.Context, *DeleteSRPolicyInput) (*RequestStatus, error)
	DeleteSRPolicyWithoutLinkState(context.Context, *DeleteSRPolicyInput) (*RequestStatus, error)
	GetSessionList(context.Context, *emptypb.Empty) (*SessionList, error)
	GetSRPolicyList(context.Context, *emptypb.Empty) (*SRPolicyList, error)
	GetTED(context.Context, *emptypb.Empty) (*TED, error)
	DeleteSession(context.Context, *Session) (*RequestStatus, error)
	mustEmbedUnimplementedPCEServiceServer()
}

// UnimplementedPCEServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPCEServiceServer struct {
}

func (UnimplementedPCEServiceServer) CreateSRPolicy(context.Context, *CreateSRPolicyInput) (*RequestStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSRPolicy not implemented")
}
func (UnimplementedPCEServiceServer) CreateSRPolicyWithoutLinkState(context.Context, *CreateSRPolicyInput) (*RequestStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSRPolicyWithoutLinkState not implemented")
}
func (UnimplementedPCEServiceServer) DeleteSRPolicy(context.Context, *DeleteSRPolicyInput) (*RequestStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSRPolicy not implemented")
}
func (UnimplementedPCEServiceServer) DeleteSRPolicyWithoutLinkState(context.Context, *DeleteSRPolicyInput) (*RequestStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSRPolicyWithoutLinkState not implemented")
}
func (UnimplementedPCEServiceServer) GetSessionList(context.Context, *emptypb.Empty) (*SessionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionList not implemented")
}
func (UnimplementedPCEServiceServer) GetSRPolicyList(context.Context, *emptypb.Empty) (*SRPolicyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSRPolicyList not implemented")
}
func (UnimplementedPCEServiceServer) GetTED(context.Context, *emptypb.Empty) (*TED, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTED not implemented")
}
func (UnimplementedPCEServiceServer) DeleteSession(context.Context, *Session) (*RequestStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedPCEServiceServer) mustEmbedUnimplementedPCEServiceServer() {}

// UnsafePCEServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PCEServiceServer will
// result in compilation errors.
type UnsafePCEServiceServer interface {
	mustEmbedUnimplementedPCEServiceServer()
}

func RegisterPCEServiceServer(s grpc.ServiceRegistrar, srv PCEServiceServer) {
	s.RegisterService(&PCEService_ServiceDesc, srv)
}

func _PCEService_CreateSRPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSRPolicyInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).CreateSRPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PCEService/CreateSRPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).CreateSRPolicy(ctx, req.(*CreateSRPolicyInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_CreateSRPolicyWithoutLinkState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSRPolicyInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).CreateSRPolicyWithoutLinkState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PCEService/CreateSRPolicyWithoutLinkState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).CreateSRPolicyWithoutLinkState(ctx, req.(*CreateSRPolicyInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_DeleteSRPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSRPolicyInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).DeleteSRPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PCEService/DeleteSRPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).DeleteSRPolicy(ctx, req.(*DeleteSRPolicyInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_DeleteSRPolicyWithoutLinkState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSRPolicyInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).DeleteSRPolicyWithoutLinkState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PCEService/DeleteSRPolicyWithoutLinkState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).DeleteSRPolicyWithoutLinkState(ctx, req.(*DeleteSRPolicyInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetSessionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetSessionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PCEService/GetSessionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetSessionList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetSRPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetSRPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PCEService/GetSRPolicyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetSRPolicyList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetTED_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetTED(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PCEService/GetTED",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetTED(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PCEService/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).DeleteSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

// PCEService_ServiceDesc is the grpc.ServiceDesc for PCEService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PCEService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PCEService",
	HandlerType: (*PCEServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSRPolicy",
			Handler:    _PCEService_CreateSRPolicy_Handler,
		},
		{
			MethodName: "CreateSRPolicyWithoutLinkState",
			Handler:    _PCEService_CreateSRPolicyWithoutLinkState_Handler,
		},
		{
			MethodName: "DeleteSRPolicy",
			Handler:    _PCEService_DeleteSRPolicy_Handler,
		},
		{
			MethodName: "DeleteSRPolicyWithoutLinkState",
			Handler:    _PCEService_DeleteSRPolicyWithoutLinkState_Handler,
		},
		{
			MethodName: "GetSessionList",
			Handler:    _PCEService_GetSessionList_Handler,
		},
		{
			MethodName: "GetSRPolicyList",
			Handler:    _PCEService_GetSRPolicyList_Handler,
		},
		{
			MethodName: "GetTED",
			Handler:    _PCEService_GetTED_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _PCEService_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pola.proto",
}
