# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pola.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npola.proto\x12\x02pb\"$\n\x05Label\x12\x0b\n\x03sid\x18\x01 \x01(\r\x12\x0e\n\x06loAddr\x18\x02 \x01(\x0c\"\x82\x01\n\x07LspData\x12\x17\n\x0fpcepSessionAddr\x18\x01 \x01(\x0c\x12\x0f\n\x07srcAddr\x18\x02 \x01(\x0c\x12\x0f\n\x07\x64stAddr\x18\x03 \x01(\x0c\x12\x19\n\x06labels\x18\x04 \x03(\x0b\x32\t.pb.Label\x12\r\n\x05\x63olor\x18\x05 \x01(\r\x12\x12\n\npolicyName\x18\x06 \x01(\t\"\x1e\n\tLspStatus\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x32\x37\n\nPceService\x12)\n\tCreateLsp\x12\x0b.pb.LspData\x1a\r.pb.LspStatus\"\x00\x42!Z\x1fgithub.com/nttcom/pola/api/grpcb\x06proto3')



_LABEL = DESCRIPTOR.message_types_by_name['Label']
_LSPDATA = DESCRIPTOR.message_types_by_name['LspData']
_LSPSTATUS = DESCRIPTOR.message_types_by_name['LspStatus']
Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), {
  'DESCRIPTOR' : _LABEL,
  '__module__' : 'pola_pb2'
  # @@protoc_insertion_point(class_scope:pb.Label)
  })
_sym_db.RegisterMessage(Label)

LspData = _reflection.GeneratedProtocolMessageType('LspData', (_message.Message,), {
  'DESCRIPTOR' : _LSPDATA,
  '__module__' : 'pola_pb2'
  # @@protoc_insertion_point(class_scope:pb.LspData)
  })
_sym_db.RegisterMessage(LspData)

LspStatus = _reflection.GeneratedProtocolMessageType('LspStatus', (_message.Message,), {
  'DESCRIPTOR' : _LSPSTATUS,
  '__module__' : 'pola_pb2'
  # @@protoc_insertion_point(class_scope:pb.LspStatus)
  })
_sym_db.RegisterMessage(LspStatus)

_PCESERVICE = DESCRIPTOR.services_by_name['PceService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037github.com/nttcom/pola/api/grpc'
  _LABEL._serialized_start=18
  _LABEL._serialized_end=54
  _LSPDATA._serialized_start=57
  _LSPDATA._serialized_end=187
  _LSPSTATUS._serialized_start=189
  _LSPSTATUS._serialized_end=219
  _PCESERVICE._serialized_start=221
  _PCESERVICE._serialized_end=276
# @@protoc_insertion_point(module_scope)
