# Copyright (c) 2022 NTT Communications Corporation
#
# This software is released under the MIT License.
# see https://github.com/nttcom/pola/blob/main/LICENSE

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pola_pb2 as pola__pb2


class PceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLsp = channel.unary_unary(
                '/pb.PceService/CreateLsp',
                request_serializer=pola__pb2.LspData.SerializeToString,
                response_deserializer=pola__pb2.LspStatus.FromString,
                )


class PceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateLsp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLsp': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLsp,
                    request_deserializer=pola__pb2.LspData.FromString,
                    response_serializer=pola__pb2.LspStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.PceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLsp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.PceService/CreateLsp',
            pola__pb2.LspData.SerializeToString,
            pola__pb2.LspStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
