name: EditorConfig Checker

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c # v2.2.0
      - run: editorconfig-checker
