name: EditorConfig Checker

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: editorconfig-checker/action-editorconfig-checker@d2ed4fd072ae6f887e9407c909af0f585d2ad9f4 # v2
      - run: editorconfig-checker
